
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/SpringClud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: a4183129CF*
  main:
      allow-bean-definition-overriding: true
  rabbitmq:
    virtual-host: /
    host: 192.168.0.104
    username: wozoucf
    password: a4183129cf
  redis:
    port: 6379
    host: 192.168.0.104
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
zuul:
   routes:
      # product: /myProduct/**
      product:
         path: /myProduct/**
         serviceId: product
         sensitiveHeaders:

   #ignored-patterns: /**/product/list
server:
  port: 8086
