spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/SpringClud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: a4183129CF*
  rabbitmq:
    virtual-host: /test
    host: 192.168.0.104
    username: wozoucf
    password: a4183129cf
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://server1:8761/eureka/
logging:
  level:
    root: info
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8085
